project:
  type: book
  output-dir: docs

book:
  title: "Tidier.jl Learning"
  author: "math4mads"
  date: "12/11/2023"
  chapters:
    - index.qmd
    - ./chapters/movie dataset.qmd
    - ./chapters/@select.qmd
    - ./chapters/@rename.qmd
    - ./chapters/summary.qmd
    #- ./chapters/references.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
  #pdf:
    #documentclass: scrreprt



