project:
  type: book
  output-dir: docs

book:
  title: "Tidier.jl Learning"
  author: "math4mads"
  date: "12/11/2023"
  chapters:
    - index.qmd
    - movie dataset.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt



